# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SimpleInterfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

# Obtiene la ruta del directorio actual donde se encuentra el script
image_path = os.path.join('/home/juancruz/PincherArm_catkin_ws/src/test_movements/scripts/large.png')

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 575)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, -10, 691, 551))
        self.widget.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 60, 641, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Wrist = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Wrist.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.Wrist.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0.534, x2:0.0454091, y2:0.534, stop:0.784091 rgba(167, 209, 241, 255), stop:1 rgba(0, 0, 0, 255));\n"
"    height: 10px;\n"
"    border: 1px solid black;\n"
"    }\n"
"QSlider::handle:horizontal {\n"
"    background-color: white;\n"
"    border: 1px solid;\n"
"    height: 20px;\n"
"    width: 15px;\n"
"    margin: 0px 0px;\n"
"    border-radius:2px;\n"
"    }\n"
"")
        self.Wrist.setMinimum(-180)
        self.Wrist.setMaximum(180)
        self.Wrist.setOrientation(QtCore.Qt.Horizontal)
        self.Wrist.setObjectName("Wrist")
        self.gridLayout.addWidget(self.Wrist, 1, 1, 1, 1)
        self.Shoulder = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Shoulder.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.Shoulder.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0.534, x2:0.0454091, y2:0.534, stop:0.784091 rgba(167, 209, 241, 255), stop:1 rgba(0, 0, 0, 255));\n"
"    height: 10px;\n"
"    border: 1px solid black;\n"
"    }\n"
"QSlider::handle:horizontal {\n"
"    background-color: white;\n"
"    border: 1px solid;\n"
"    height: 20px;\n"
"    width: 15px;\n"
"    margin: 0px 0px;\n"
"    border-radius:2px;\n"
"    }\n"
"")
        self.Shoulder.setMinimum(-200)
        self.Shoulder.setMaximum(200)
        self.Shoulder.setOrientation(QtCore.Qt.Horizontal)
        self.Shoulder.setObjectName("Shoulder")
        self.gridLayout.addWidget(self.Shoulder, 3, 1, 1, 1)
        self.Elbow = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Elbow.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.Elbow.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0.534, x2:0.0454091, y2:0.534, stop:0.784091 rgba(167, 209, 241, 255), stop:1 rgba(0, 0, 0, 255));\n"
"    height: 10px;\n"
"    border: 1px solid black;\n"
"    }\n"
"QSlider::handle:horizontal {\n"
"    background-color: white;\n"
"    border: 1px solid;\n"
"    height: 20px;\n"
"    width: 15px;\n"
"    margin: 0px 0px;\n"
"    border-radius:2px;\n"
"    }\n"
"")
        self.Elbow.setMinimum(-250)
        self.Elbow.setMaximum(250)
        self.Elbow.setOrientation(QtCore.Qt.Horizontal)
        self.Elbow.setObjectName("Elbow")
        self.gridLayout.addWidget(self.Elbow, 2, 1, 1, 1)
        self.Pan = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Pan.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.Pan.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0.534, x2:0.0454091, y2:0.534, stop:0.784091 rgba(167, 209, 241, 255), stop:1 rgba(0, 0, 0, 255));\n"
"    height: 10px;\n"
"    border: 1px solid black;\n"
"    }\n"
"QSlider::handle:horizontal {\n"
"    background-color: white;\n"
"    border: 1px solid;\n"
"    height: 20px;\n"
"    width: 15px;\n"
"    margin: 0px 0px;\n"
"    border-radius:2px;\n"
"    }\n"
"")
        self.Pan.setMinimum(-260)
        self.Pan.setMaximum(260)
        self.Pan.setOrientation(QtCore.Qt.Horizontal)
        self.Pan.setObjectName("Pan")
        self.gridLayout.addWidget(self.Pan, 4, 1, 1, 1)
        self.LabelGripper = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelGripper.setStyleSheet("QLabel{\n"
"    font: 75 9pt \"Times New Roman\";\n"
"    text-decoration: underline;\n"
"    background-color: rgb(223, 223, 223);\n"
"    border: 1.5px solid black;\n"
"    border-top-left-radius :10px;\n"
"    border-bottom-left-radius : 15px;\n"
"    min-width: 10em;\n"
"    padding: 5px;\n"
"}")
        self.LabelGripper.setObjectName("LabelGripper")
        self.gridLayout.addWidget(self.LabelGripper, 0, 0, 1, 1)
        self.LabelWrist = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelWrist.setStyleSheet("QLabel{\n"
"    font: 75 9pt \"Times New Roman\";\n"
"    text-decoration: underline;\n"
"    background-color: rgb(223, 223, 223);\n"
"    border: 1.5px solid black;\n"
"    border-top-left-radius :10px;\n"
"    border-bottom-left-radius : 15px;\n"
"    min-width: 8em;\n"
"    padding: 5px;\n"
"}")
        self.LabelWrist.setObjectName("LabelWrist")
        self.gridLayout.addWidget(self.LabelWrist, 1, 0, 1, 1)
        self.LabelShoulder = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelShoulder.setStyleSheet("QLabel{\n"
"    font: 75 9pt \"Times New Roman\";\n"
"    text-decoration: underline;\n"
"    background-color: rgb(223, 223, 223);\n"
"    border: 1.5px solid black;\n"
"    border-top-left-radius :10px;\n"
"    border-bottom-left-radius : 15px;\n"
"    min-width: 8em;\n"
"    padding: 5px;\n"
"}")
        self.LabelShoulder.setObjectName("LabelShoulder")
        self.gridLayout.addWidget(self.LabelShoulder, 3, 0, 1, 1)
        self.LabelPan = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelPan.setStyleSheet("QLabel{\n"
"    font: 75 9pt \"Times New Roman\";\n"
"    text-decoration: underline;\n"
"    background-color: rgb(223, 223, 223);\n"
"    border: 1.5px solid black;\n"
"    border-top-left-radius :10px;\n"
"    border-bottom-left-radius : 15px;\n"
"    min-width: 8em;\n"
"    padding: 5px;\n"
"}")
        self.LabelPan.setObjectName("LabelPan")
        self.gridLayout.addWidget(self.LabelPan, 4, 0, 1, 1)
        self.Gripper = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Gripper.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.Gripper.setMouseTracking(False)
        self.Gripper.setAutoFillBackground(False)
        self.Gripper.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0.534, x2:0.0454091, y2:0.534, stop:0.784091 rgba(167, 209, 241, 255), stop:1 rgba(0, 0, 0, 255));\n"
"    height: 10px;\n"
"    border: 1px solid black;\n"
"    }\n"
"QSlider::handle:horizontal {\n"
"    background-color: white;\n"
"    border: 1px solid;\n"
"    height: 20px;\n"
"    width: 15px;\n"
"    margin: 0px 0px;\n"
"    border-radius:2px;\n"
"    }\n"
"")
        self.Gripper.setMinimum(-260)
        self.Gripper.setMaximum(180)
        self.Gripper.setOrientation(QtCore.Qt.Horizontal)
        self.Gripper.setObjectName("Gripper")
        self.gridLayout.addWidget(self.Gripper, 0, 1, 1, 1)
        self.ButtonWrist = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ButtonWrist.setStyleSheet("QPushButton{\n"
"    font: 81 8pt \"Rockwell Extra Bold\";\n"
"    text-decoration: underline;\n"
"    border: 1.5px solid black;\n"
"    border-top-right-radius :10px;\n"
"    border-bottom-right-radius : 15px;\n"
"    min-width: 1em;\n"
"    padding: 5px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"}")
        self.ButtonWrist.setObjectName("ButtonWrist")
        self.gridLayout.addWidget(self.ButtonWrist, 1, 2, 1, 1)
        self.ButtonElbow = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ButtonElbow.setStyleSheet("QPushButton{\n"
"    font: 81 8pt \"Rockwell Extra Bold\";\n"
"    text-decoration: underline;\n"
"    border: 1.5px solid black;\n"
"    border-top-right-radius :10px;\n"
"    border-bottom-right-radius : 15px;\n"
"    min-width: 1em;\n"
"    padding: 5px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"}")
        self.ButtonElbow.setObjectName("ButtonElbow")
        self.gridLayout.addWidget(self.ButtonElbow, 2, 2, 1, 1)
        self.ButtonShoulder = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ButtonShoulder.setStyleSheet("QPushButton{\n"
"    font: 81 8pt \"Rockwell Extra Bold\";\n"
"    text-decoration: underline;\n"
"    border: 1.5px solid black;\n"
"    border-top-right-radius :10px;\n"
"    border-bottom-right-radius : 15px;\n"
"    min-width: 1em;\n"
"    padding: 5px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"}")
        self.ButtonShoulder.setObjectName("ButtonShoulder")
        self.gridLayout.addWidget(self.ButtonShoulder, 3, 2, 1, 1)
        self.ButtonPan = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ButtonPan.setStyleSheet("QPushButton{\n"
"    font: 81 8pt \"Rockwell Extra Bold\";\n"
"    text-decoration: underline;\n"
"    border: 1.5px solid black;\n"
"    border-top-right-radius :10px;\n"
"    border-bottom-right-radius : 15px;\n"
"    min-width: 1em;\n"
"    padding: 5px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"}")
        self.ButtonPan.setObjectName("ButtonPan")
        self.gridLayout.addWidget(self.ButtonPan, 4, 2, 1, 1)
        self.LabelElbow = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelElbow.setStyleSheet("QLabel{\n"
"    font: 75 9pt \"Times New Roman\";\n"
"    text-decoration: underline;\n"
"    background-color: rgb(223, 223, 223);\n"
"    border: 1.5px solid black;\n"
"    border-top-left-radius :10px;\n"
"    border-bottom-left-radius : 15px;\n"
"    min-width: 8em;\n"
"    padding: 5px;\n"
"}")
        self.LabelElbow.setObjectName("LabelElbow")
        self.gridLayout.addWidget(self.LabelElbow, 2, 0, 1, 1)
        self.ButtonGrip = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ButtonGrip.setStyleSheet("QPushButton{\n"
"    font: 81 8pt \"Rockwell Extra Bold\";\n"
"    text-decoration: underline;\n"
"    border: 1.5px solid black;\n"
"    border-top-right-radius :10px;\n"
"    border-bottom-right-radius : 15px;\n"
"    min-width: 1em;\n"
"    padding: 5px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"}")
        self.ButtonGrip.setAutoDefault(False)
        self.ButtonGrip.setFlat(False)
        self.ButtonGrip.setObjectName("ButtonGrip")
        self.gridLayout.addWidget(self.ButtonGrip, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(120, 20, 491, 31))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("font: 87 18pt \"Segoe UI Black\";\n"
"background-color: rgb(235, 235, 235);\n"
"border-color: rgb(165, 165, 165);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(200, 270, 246, 61))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ReEna = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ReEna.setStyleSheet("QPushButton{\n"
"    background-color: rgb(200, 200, 200);\n"
"    border: 1.5px solid black;\n"
"    border-radius :15px;\n"
"    font: bold 14px;\n"
"    min-width: 3em;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(224, 0, 0);\n"
"    border: 2px solid white;\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.ReEna.setObjectName("ReEna")
        self.gridLayout_2.addWidget(self.ReEna, 0, 0, 1, 1)
        self.Home = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Home.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 0);\n"
"    border: 1.5px solid black;\n"
"    border-radius :15px;\n"
"    font: bold 14px;\n"
"    min-width: 3em;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(255, 170, 0);\n"
"    border: 2px solid white;\n"
"    color: red;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.Home.setObjectName("Home")
        self.gridLayout_2.addWidget(self.Home, 0, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(30, 270, 164, 261))
        self.widget_2.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-top-left-radius :15px;\n"
"border-bottom-left-radius : 30px;")
        self.widget_2.setObjectName("widget_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.widget_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 40, 141, 213))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_5.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(170, 170, 255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_2.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(170, 170, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_4.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(170, 170, 255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 1, 1, 1)
        self.Directa_X = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.Directa_X.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(255, 255, 255);\n"
"min-width: 5em;\n"
"padding: 3px;\n"
"border: 1px solid black;")
        self.Directa_X.setText("")
        self.Directa_X.setObjectName("Directa_X")
        self.gridLayout_3.addWidget(self.Directa_X, 0, 1, 1, 1)
        self.Directa_Z = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.Directa_Z.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(255, 255, 255);\n"
"min-width: 5em;\n"
"padding: 3px;\n"
"border: 1px solid black;")
        self.Directa_Z.setText("")
        self.Directa_Z.setObjectName("Directa_Z")
        self.gridLayout_3.addWidget(self.Directa_Z, 2, 1, 1, 1)
        self.Directa_Y = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.Directa_Y.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(255, 255, 255);\n"
"min-width: 5em;\n"
"padding: 3px;\n"
"border: 1px solid black;")
        self.Directa_Y.setText("")
        self.Directa_Y.setObjectName("Directa_Y")
        self.gridLayout_3.addWidget(self.Directa_Y, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_3.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(170, 170, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 4, 0, 1, 1)
        self.Directa_Roll = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.Directa_Roll.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(255, 255, 255);\n"
"min-width: 5em;\n"
"padding: 3px;\n"
"border: 1px solid black;")
        self.Directa_Roll.setText("")
        self.Directa_Roll.setObjectName("Directa_Roll")
        self.gridLayout_3.addWidget(self.Directa_Roll, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_7.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(170, 170, 255);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 5, 0, 1, 1)
        self.Directa_Pitch = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.Directa_Pitch.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(255, 255, 255);\n"
"min-width: 5em;\n"
"padding: 3px;\n"
"border: 1px solid black;")
        self.Directa_Pitch.setText("")
        self.Directa_Pitch.setObjectName("Directa_Pitch")
        self.gridLayout_3.addWidget(self.Directa_Pitch, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_6.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(170, 170, 255);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 6, 0, 1, 1)
        self.Directa_Yawl = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.Directa_Yawl.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(255, 255, 255);\n"
"min-width: 5em;\n"
"padding: 3px;\n"
"border: 1px solid black;")
        self.Directa_Yawl.setText("")
        self.Directa_Yawl.setObjectName("Directa_Yawl")
        self.gridLayout_3.addWidget(self.Directa_Yawl, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 141, 20))
        self.label_8.setStyleSheet("font: bold 10px;\n"
"background-color: rgb(149, 149, 223);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(230, 380, 191, 111))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(image_path))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(510, 270, 164, 261))
        self.widget_3.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-top-right-radius :15px;\n"
"border-bottom-right-radius : 30px;")
        self.widget_3.setObjectName("widget_3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.widget_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 40, 150, 121))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Inverse_Z = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.Inverse_Z.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(255, 255, 255);\n"
"min-width: 5em;\n"
"padding: 3px;\n"
"border: 1px solid black;")
        self.Inverse_Z.setObjectName("Inverse_Z")
        self.gridLayout_4.addWidget(self.Inverse_Z, 2, 1, 1, 1)
        self.Inverse_Y = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.Inverse_Y.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(255, 255, 255);\n"
"min-width: 5em;\n"
"padding: 3px;\n"
"border: 1px solid black;")
        self.Inverse_Y.setObjectName("Inverse_Y")
        self.gridLayout_4.addWidget(self.Inverse_Y, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_14.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(170, 170, 255);")
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_12.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(170, 170, 255);")
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_15.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(170, 170, 255);")
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 0, 1, 1)
        self.Inverse_X = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.Inverse_X.setStyleSheet("font: bold 16px;\n"
"background-color: rgb(255, 255, 255);\n"
"min-width: 4em;\n"
"padding: 3px;\n"
"border: 1px solid black;")
        self.Inverse_X.setObjectName("Inverse_X")
        self.gridLayout_4.addWidget(self.Inverse_X, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget_3)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 141, 20))
        self.label_20.setStyleSheet("font: bold 10px;\n"
"background-color: rgb(149, 149, 223);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.widget_3)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(9, 199, 151, 62))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Calculate = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.Calculate.setStyleSheet("QPushButton{\n"
"    font: 81 7pt \"Rockwell Extra Bold\";\n"
"    border: 1.5px solid black;\n"
"    border-top-left-radius :10px;\n"
"    border-bottom-left-radius : 15px;\n"
"    min-width: 1em;\n"
"    padding: 5px;\n"
"    background-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(255, 170, 0);\n"
"    border: 2px solid white;\n"
"    color: red;\n"
"}")
        self.Calculate.setObjectName("Calculate")
        self.gridLayout_5.addWidget(self.Calculate, 0, 0, 1, 1)
        self.Star = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.Star.setStyleSheet("QPushButton{\n"
"    font: 81 8pt \"Rockwell Extra Bold\";\n"
"    text-decoration: underline;\n"
"    border: 1.5px solid black;\n"
"    border-top-right-radius :10px;\n"
"    border-bottom-right-radius : 15px;\n"
"    min-width: 1em;\n"
"    padding: 5px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: rgb(255, 170, 0);\n"
"    border: 2px solid white;\n"
"    color: red;\n"
"}")
        self.Star.setObjectName("Star")
        self.gridLayout_5.addWidget(self.Star, 0, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 160, 151, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Advertencia = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Advertencia.setStyleSheet("font: bold 10px;\n"
"background-color: rgb(255, 254, 201);\n"
"min-width: 1em;\n"
"padding: 2px;\n"
"border: 1px solid black;\n"
"")
        self.Advertencia.setText("")
        self.Advertencia.setScaledContents(True)
        self.Advertencia.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Advertencia.setObjectName("Advertencia")
        self.verticalLayout_2.addWidget(self.Advertencia)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(0, 10, 691, 531))
        self.label_13.setStyleSheet("background-color: rgb(138, 138, 138);\n"
"border-radius:15px;\n"
"border: 5px solid rgb(29, 29, 29);\n"
"")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_13.raise_()
        self.gridLayoutWidget.raise_()
        self.label.raise_()
        self.gridLayoutWidget_2.raise_()
        self.widget_2.raise_()
        self.label_10.raise_()
        self.widget_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LabelGripper.setText(_translate("MainWindow", "Gripper: "))
        self.LabelWrist.setText(_translate("MainWindow", "Arm Wrist Flex:"))
        self.LabelShoulder.setText(_translate("MainWindow", "Arm Shoulder Lift:"))
        self.LabelPan.setText(_translate("MainWindow", "Arm Shoulder Pan:"))
        self.ButtonWrist.setText(_translate("MainWindow", "OFF"))
        self.ButtonElbow.setText(_translate("MainWindow", "OFF"))
        self.ButtonShoulder.setText(_translate("MainWindow", "OFF"))
        self.ButtonPan.setText(_translate("MainWindow", "OFF"))
        self.LabelElbow.setText(_translate("MainWindow", "Arm Elbow Flex:"))
        self.ButtonGrip.setText(_translate("MainWindow", "OFF"))
        self.label.setText(_translate("MainWindow", "Movement and Reading of Joints"))
        self.ReEna.setText(_translate("MainWindow", "RELAX"))
        self.Home.setText(_translate("MainWindow", "HOME"))
        self.label_5.setText(_translate("MainWindow", "z:"))
        self.label_2.setText(_translate("MainWindow", "x:"))
        self.label_4.setText(_translate("MainWindow", "y:"))
        self.label_3.setText(_translate("MainWindow", "R:"))
        self.label_7.setText(_translate("MainWindow", "P:"))
        self.label_6.setText(_translate("MainWindow", "Y:"))
        self.label_8.setText(_translate("MainWindow", "TCP (Tool Center Point):"))
        self.label_14.setText(_translate("MainWindow", "Xo ="))
        self.label_12.setText(_translate("MainWindow", "Zo ="))
        self.label_15.setText(_translate("MainWindow", "Yo ="))
        self.label_20.setText(_translate("MainWindow", "Inverse Kinematics"))
        self.Calculate.setText(_translate("MainWindow", "Calculate"))
        self.Star.setText(_translate("MainWindow", "Star"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
